name: CI

on:
  pull_request: null
  push:
    branches:
      - master
      - 3.5.x

jobs:
  Tests:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental == true }}
    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.0'
          - '7.4'
          - '7.3'
          - '7.2'
        sentry_constraint: [false]
        symfony_constraint: [false]
        experimental: [false]
        include:
          - description: 'Symfony 5.0'
            php: '8.0'
            symfony_constraint: 5.0.*
          - description: 'Symfony 5.0'
            php: '7.4'
            symfony_constraint: 5.0.*
          - description: 'Symfony 4.4'
            php: '8.0'
            symfony_constraint: 4.4.*
          - description: 'Symfony 4.4'
            php: '7.4'
            symfony_constraint: 4.4.*
          - description: 'Symfony 3.4'
            php: '7.2'
            symfony_constraint: 3.4.*
            env:
              SYMFONY_DEPRECATIONS_HELPER: disabled
          - description: 'prefer lowest'
            php: '7.2'
            composer_option: '--prefer-lowest'
            env:
              SYMFONY_DEPRECATIONS_HELPER: disabled

    name: PHP ${{ matrix.php }} tests (${{ matrix.description }})
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: ${{ matrix.php }}-${{ matrix.symfony_constraint }}-${{ matrix.composer_option }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Update Symfony Composer Version
        run: |
          sed -ri '/symfony\/(monolog-bundle|phpunit-bridge|messenger|psr-http-message-bridge|polyfill-php80)/! s/"symfony\/(.+)": "(.+)"/"symfony\/\1": "'${{ matrix.symfony_constraint }}'"/' composer.json;
        if: matrix.symfony_constraint

      - name: Remove Symfony Messenger
        run: composer remove --dev symfony/messenger --no-update
        if: matrix.symfony_constraint == '3.4.*' || matrix.composer_option == '--prefer-lowest'

      - name: Install dependencies
        run: composer update --no-progress --ansi ${{ matrix.composer_option }}

      - name: Install Sentry
        run: composer require sentry/sentry dev-develop
        if: matrix.sentry_constraint == 'dev-develop'

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Run codecov
        uses: codecov/codecov-action@v1
        with:
          file: './coverage.xml'
          fail_ci_if_error: true
